server: 
  port: 8080
spring:
   kafka:
     producer:
        bootstrap-servers: ${IP_KAFKA_SERVER}:${KAFKA_PORT}
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
auto: 
  create: 
    topics: 
      enable: true